# Generated by Django 5.1 on 2024-09-12 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("git_post", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repository",
            name="image",
            field=models.ImageField(
                blank=True,
                default="git_post/git_image.png",
                null=True,
                upload_to="git_post/",
            ),
        ),
    ]
